//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeddingAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album image is required..
        /// </summary>
        internal static string AlbumImageRequired {
            get {
                return ResourceManager.GetString("AlbumImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name is required..
        /// </summary>
        internal static string AlbumNameRequired {
            get {
                return ResourceManager.GetString("AlbumNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album not found..
        /// </summary>
        internal static string AlbumNotFound {
            get {
                return ResourceManager.GetString("AlbumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad session token..
        /// </summary>
        internal static string BadTokenMessage {
            get {
                return ResourceManager.GetString("BadTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is missing..
        /// </summary>
        internal static string EmailOrPassMissingMessage {
            get {
                return ResourceManager.GetString("EmailOrPassMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened during sending message from server..
        /// </summary>
        internal static string ErrorSendMessage {
            get {
                return ResourceManager.GetString("ErrorSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found..
        /// </summary>
        internal static string ImageNotFoundMessage {
            get {
                return ResourceManager.GetString("ImageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is invalid..
        /// </summary>
        internal static string InvalidAuthDataMessage {
            get {
                return ResourceManager.GetString("InvalidAuthDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, upload photo..
        /// </summary>
        internal static string NoPhotoMessage {
            get {
                return ResourceManager.GetString("NoPhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        internal static string NotFountMessage {
            get {
                return ResourceManager.GetString("NotFountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required data is missing.
        /// </summary>
        internal static string RequiredDataMissing {
            get {
                return ResourceManager.GetString("RequiredDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required email is missing.
        /// </summary>
        internal static string RequiredEmailMissing {
            get {
                return ResourceManager.GetString("RequiredEmailMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required message is missing.
        /// </summary>
        internal static string RequiredMessageMissing {
            get {
                return ResourceManager.GetString("RequiredMessageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required name is missing.
        /// </summary>
        internal static string RequiredNameMissing {
            get {
                return ResourceManager.GetString("RequiredNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type is not supported..
        /// </summary>
        internal static string UnsupportedMediaTypeMessage {
            get {
                return ResourceManager.GetString("UnsupportedMediaTypeMessage", resourceCulture);
            }
        }
    }
}
